DROP TABLE ABSANCE;
DROP TABLE NOTE;
DROP TABLE HISTORIQUE_PROMOTION;
DROP TABLE ENSEIGNE;
DROP TABLE PROMOTION;
DROP TABLE ETUDIANT;
DROP TABLE MATIERE;
DROP TABLE ENSEIGNANT;

CREATE TABLE ENSEIGNANT
(
    ID number PRIMARY KEY,
    NOM varchar2(255) NOT NULL,
    PRENOM varchar2(255) NOT NULL,
    EMAIL varchar2(255) NOT NULL UNIQUE,
    DATE_ENTREE date DEFAULT SYSDATE NOT NULL
);

CREATE TABLE MATIERE
(
    ID number PRIMARY KEY,
    NOM varchar2(255) NOT NULL
);

CREATE TABLE ENSEIGNE
(
    ID_ENSEIGNANT number NOT NULL,
    ID_MATIERE number NOT NULL,

    PRIMARY KEY (ID_ENSEIGNANT, ID_MATIERE),
    FOREIGN KEY (ID_ENSEIGNANT) REFERENCES ENSEIGNANT(ID),
    FOREIGN KEY (ID_MATIERE) REFERENCES MATIERE(ID)
);

CREATE TABLE ETUDIANT
(
    ID number PRIMARY KEY,
    NOM varchar2(255) NOT NULL,
    PRENOM varchar2(255) NOT NULL,
    EMAIL varchar2(255) NOT NULL UNIQUE
);

CREATE TABLE PROMOTION
(
    ID number PRIMARY KEY,
    ANNEE_SCOLAIRE varchar2(9) NOT NULL,
    NIVEAU_ETUDE varchar2(255)
);

CREATE TABLE HISTORIQUE_PROMOTION
(
    ID_PROMOTION number NOT NULL,
    ID_ETUDIANT number NOT NULL,

    PRIMARY KEY (ID_PROMOTION, ID_ETUDIANT),
    FOREIGN KEY (ID_PROMOTION) REFERENCES PROMOTION(ID),
    FOREIGN KEY (ID_ETUDIANT) REFERENCES ETUDIANT(ID)
);

CREATE TABLE NOTE
(
    ID number PRIMARY KEY,
    ID_ETUDIANT number NOT NULL,
    ID_ENSEIGNANT number NOT NULL,
    ID_MATIERE number NOT NULL,
    NOTE number NOT NULL,
    DATE_PUBLICATION date DEFAULT SYSDATE NOT NULL,

    FOREIGN KEY (ID_ETUDIANT) REFERENCES ETUDIANT(ID),
    FOREIGN KEY (ID_ENSEIGNANT) REFERENCES ENSEIGNANT(ID),
    FOREIGN KEY (ID_MATIERE) REFERENCES MATIERE(ID)
);

CREATE TABLE ABSANCE
(
    ID number PRIMARY KEY,
    ID_ETUDIANT number NOT NULL,
    DATE_ABSANCE date NOT NULL,
    MINUTES_ABSANCE number NOT NULL,
    JUSTIFICATION varchar2(255),

    FOREIGN KEY (ID_ETUDIANT) REFERENCES ETUDIANT(ID)
);