DROP TABLE ABSANCE;
DROP TABLE NOTE;
DROP TABLE HISTORIQUE_PROMOTION;
DROP TABLE ENSEIGNE;
DROP TABLE PROMOTION;
DROP TABLE ETUDIANT;
DROP TABLE MATIERE;
DROP TABLE ENSEIGNANT;

CREATE TABLE ENSEIGNANT
(
    ID number PRIMARY KEY,
    NOM varchar2(255) NOT NULL,
    PRENOM varchar2(255) NOT NULL,
    EMAIL varchar2(255) NOT NULL UNIQUE,
    DATE_ENTREE date DEFAULT SYSDATE NOT NULL
);

CREATE TABLE MATIERE
(
    ID number PRIMARY KEY,
    NOM varchar2(255) NOT NULL
);

CREATE TABLE ENSEIGNE
(
    ID_ENSEIGNANT number NOT NULL,
    ID_MATIERE number NOT NULL,

    PRIMARY KEY (ID_ENSEIGNANT, ID_MATIERE),
    FOREIGN KEY (ID_ENSEIGNANT) REFERENCES ENSEIGNANT(ID),
    FOREIGN KEY (ID_MATIERE) REFERENCES MATIERE(ID)
);

CREATE TABLE ETUDIANT
(
    ID number PRIMARY KEY,
    NOM varchar2(255) NOT NULL,
    PRENOM varchar2(255) NOT NULL,
    EMAIL varchar2(255) NOT NULL UNIQUE
);

CREATE TABLE PROMOTION
(
    ID number PRIMARY KEY,
    ANNEE_SCOLAIRE varchar2(9) NOT NULL,
    NIVEAU_ETUDE varchar2(255)
);

CREATE TABLE HISTORIQUE_PROMOTION
(
    ID_PROMOTION number NOT NULL,
    ID_ETUDIANT number NOT NULL,

    PRIMARY KEY (ID_PROMOTION, ID_ETUDIANT),
    FOREIGN KEY (ID_PROMOTION) REFERENCES PROMOTION(ID),
    FOREIGN KEY (ID_ETUDIANT) REFERENCES ETUDIANT(ID)
);

CREATE TABLE NOTE
(
    ID number PRIMARY KEY,
    ID_ETUDIANT number NOT NULL,
    ID_ENSEIGNANT number NOT NULL,
    ID_MATIERE number NOT NULL,
    NOTE number NOT NULL,
    DATE_PUBLICATION date DEFAULT SYSDATE NOT NULL,

    FOREIGN KEY (ID_ETUDIANT) REFERENCES ETUDIANT(ID),
    FOREIGN KEY (ID_ENSEIGNANT) REFERENCES ENSEIGNANT(ID),
    FOREIGN KEY (ID_MATIERE) REFERENCES MATIERE(ID)
);

CREATE TABLE ABSANCE
(
    ID number PRIMARY KEY,
    ID_ETUDIANT number NOT NULL,
    DATE_ABSANCE date NOT NULL,
    MINUTES_ABSANCE number NOT NULL,
    JUSTIFICATION varchar2(255),

    FOREIGN KEY (ID_ETUDIANT) REFERENCES ETUDIANT(ID)
);


INSERT ALL
        INTO ENSEIGNANT (ID, NOM, PRENOM, EMAIL) VALUES (1, 'Sachiko', 'Esther', 'sachiko.esther@school.com')
        INTO ENSEIGNANT (ID, NOM, PRENOM, EMAIL) VALUES (2, 'Katniss', 'Parastu', 'katniss.parastu@school.com')
        INTO ENSEIGNANT (ID, NOM, PRENOM, EMAIL) VALUES (3, 'Epaphroditus', 'Paula', 'epaphroditus.paula@school.com')

        INTO MATIERE VALUES (1, '1HTML')
        INTO MATIERE VALUES (2, '1WEBD')
        INTO MATIERE VALUES (3, '1SGBD')
        INTO MATIERE VALUES (4, '2HTML')
        INTO MATIERE VALUES (5, '2WEBD')
        INTO MATIERE VALUES (6, '2SGBD')
        INTO MATIERE VALUES (7, '3HTML')
        INTO MATIERE VALUES (8, '3WEBD')
        INTO MATIERE VALUES (9, '3SGBD')

        INTO ENSEIGNE VALUES (1, 1)
        INTO ENSEIGNE VALUES (2, 2)
        INTO ENSEIGNE VALUES (3, 3)
        INTO ENSEIGNE VALUES (1, 4)
        INTO ENSEIGNE VALUES (2, 5)
        INTO ENSEIGNE VALUES (3, 6)
        INTO ENSEIGNE VALUES (1, 7)
        INTO ENSEIGNE VALUES (2, 8)
        INTO ENSEIGNE VALUES (3, 9)

        INTO ETUDIANT VALUES (1, 'Aliyə', 'Elva', 'aliyə.elva@gmail.com')
        INTO ETUDIANT VALUES (2, 'René', 'Jozefa', 'rené.jozefa@gmail.com')
        INTO ETUDIANT VALUES (3, 'Tegid', 'Eavan', 'tegid.eavan@gmail.com')
        INTO ETUDIANT VALUES (4, 'Morgan','Sully', 'morgan.sully@gmail.com')
        INTO ETUDIANT VALUES (5, 'Agatha', 'Marine', 'agatha.marine@gmail.com')
        INTO ETUDIANT VALUES (6, 'Amirani', 'Katsu', 'amirani.katsu@gmail.com')
        INTO ETUDIANT VALUES (7, 'Cody', 'Dositheus', 'cody.dositheus@yahoo.fr')
        INTO ETUDIANT VALUES (8, 'Olivia', 'Sigilina', 'olivia.sigilina@yahoo.fr')
        INTO ETUDIANT VALUES (9, 'Zdislav', 'Emanuel', 'zdislav.emanuel@yahoo.fr')
        INTO ETUDIANT VALUES (10, 'Efnan', 'Lily-Rose', 'efnan.lily-rose@yahoo.fr')
        INTO ETUDIANT VALUES (11, 'Gbemisola', 'Sevinj', 'gbemsola.sevinj@yahoo.fr')
        INTO ETUDIANT VALUES (12, 'Parvina', 'Yvelise', 'parvina.yvelise@outlook.com')
        INTO ETUDIANT VALUES (13, 'Judicaël', 'Miguel', 'judicaël.miguel@outlook.com')
        INTO ETUDIANT VALUES (14, 'Marijke', 'Damodar', 'marijke.damodar@outlook.com')
        INTO ETUDIANT VALUES (15, 'Augusto', 'Theodotos', 'augusto.theodotos@outlook.com')

        INTO PROMOTION VALUES (1, '2022-2023', '1ème année')
        INTO PROMOTION VALUES (2, '2023-2024', '1ème année')
        INTO PROMOTION VALUES (3, '2023-2024', '2ème année')
        INTO PROMOTION VALUES (4, '2024-2025', '1ème année')
        INTO PROMOTION VALUES (5, '2024-2025', '2ème année')
        INTO PROMOTION VALUES (6, '2024-2025', '3ème année')

        INTO HISTORIQUE_PROMOTION VALUES (6, 1)
        INTO HISTORIQUE_PROMOTION VALUES (3, 1)
        INTO HISTORIQUE_PROMOTION VALUES (1, 1)
        INTO HISTORIQUE_PROMOTION VALUES (5, 2)
        INTO HISTORIQUE_PROMOTION VALUES (2, 2)
        INTO HISTORIQUE_PROMOTION VALUES (4, 3)
        INTO HISTORIQUE_PROMOTION VALUES (6, 4)
        INTO HISTORIQUE_PROMOTION VALUES (3, 4)
        INTO HISTORIQUE_PROMOTION VALUES (1, 4)
        INTO HISTORIQUE_PROMOTION VALUES (5, 5)
        INTO HISTORIQUE_PROMOTION VALUES (2, 5)
        INTO HISTORIQUE_PROMOTION VALUES (4, 6)
        INTO HISTORIQUE_PROMOTION VALUES (6, 7)
        INTO HISTORIQUE_PROMOTION VALUES (3, 7)
        INTO HISTORIQUE_PROMOTION VALUES (1, 7)
        INTO HISTORIQUE_PROMOTION VALUES (5, 8)
        INTO HISTORIQUE_PROMOTION VALUES (2, 8)
        INTO HISTORIQUE_PROMOTION VALUES (4, 9)
        INTO HISTORIQUE_PROMOTION VALUES (6, 10)
        INTO HISTORIQUE_PROMOTION VALUES (3, 10)
        INTO HISTORIQUE_PROMOTION VALUES (1, 10)
        INTO HISTORIQUE_PROMOTION VALUES (5, 11)
        INTO HISTORIQUE_PROMOTION VALUES (2, 11)
        INTO HISTORIQUE_PROMOTION VALUES (4, 12)
        INTO HISTORIQUE_PROMOTION VALUES (6, 13)
        INTO HISTORIQUE_PROMOTION VALUES (3, 13)
        INTO HISTORIQUE_PROMOTION VALUES (1, 13)
        INTO HISTORIQUE_PROMOTION VALUES (5, 14)
        INTO HISTORIQUE_PROMOTION VALUES (2, 14)
        INTO HISTORIQUE_PROMOTION VALUES (4, 15)

        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (1, 1, 1, 1, 72)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (2, 1, 2, 2, 46)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (3, 1, 3, 3, 61)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (4, 1, 1, 4, 79)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (5, 1, 2, 5, 88)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (6, 1, 3, 6, 65)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (7, 1, 1, 7, 41)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (8, 2, 1, 1, 40)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (9, 2, 2, 2, 53)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (10, 2, 3, 3, 92)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (11, 2, 1, 4, 72)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (12, 3, 1, 1, 89)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (13, 4, 1, 1, 58)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (14, 4, 2, 2, 91)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (15, 4, 3, 3, 85)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (16, 4, 1, 4, 74)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (17, 4, 2, 5, 35)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (18, 4, 3, 6, 63)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (19, 4, 1, 7, 64)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (20, 5, 1, 1, 86)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (21, 5, 2, 2, 45)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (22, 5, 3, 3, 52)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (23, 5, 1, 4, 47)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (24, 6, 1, 1, 43)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (25, 7, 1, 1, 91)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (26, 7, 2, 2, 61)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (27, 7, 3, 3, 63)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (28, 7, 1, 4, 65)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (29, 7, 2, 5, 67)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (30, 7, 3, 6, 96)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (31, 7, 1, 7, 57)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (32, 8, 1, 1, 48)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (33, 8, 2, 2, 77)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (34, 8, 3, 3, 83)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (35, 8, 1, 4, 89)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (36, 9, 1, 1, 100)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (37, 10, 1, 1, 84)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (38, 10, 2, 2, 55)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (39, 10, 3, 3, 73)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (40, 10, 1, 4, 65)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (41, 10, 2, 5, 50)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (42, 10, 3, 6, 37)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (43, 10, 1, 7, 59)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (44, 11, 1, 1, 74)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (45, 11, 2, 2, 99)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (46, 11, 3, 3, 74)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (47, 11, 1, 4, 68)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (48, 12, 1, 1, 77)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (49, 13, 1, 1, 58)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (50, 13, 2, 2, 96)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (51, 13, 3, 3, 100)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (52, 13, 1, 4, 76)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (53, 13, 2, 5, 56)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (54, 13, 3, 6, 39)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (55, 13, 1, 7, 78)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (56, 14, 1, 1, 94)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (57, 14, 2, 2, 57)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (58, 14, 3, 3, 88)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (59, 14, 1, 4, 42)
        INTO NOTE (ID, ID_ETUDIANT, ID_ENSEIGNANT, ID_MATIERE, NOTE) VALUES (60, 15, 1, 1, 70)

        INTO ABSANCE VALUES (1, 2, TO_DATE('18-02-2025', 'DD-MM-YYYY'), 10, NULL)
        INTO ABSANCE VALUES (2, 5, TO_DATE('28-01-2025', 'DD-MM-YYYY'), 15, 'Retard de bus')
        INTO ABSANCE VALUES (3, 6, TO_DATE('18-11-2024', 'DD-MM-YYYY'), 30, 'Panne de reveil')
        INTO ABSANCE VALUES (4, 12, TO_DATE('01-12-2024', 'DD-MM-YYYY'), 5, NULL)
        INTO ABSANCE VALUES (5, 15, TO_DATE('12-02-2025', 'DD-MM-YYYY'), 420, 'Malade')
SELECT 1 FROM DUAL;
